apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-lb
spec:
  selector:
    matchLabels:
      app: nginx
      department: prod
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        department: prod
    spec:
      containers:
      - name: hello
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50001"
