apiVersion: v1
kind: Service
metadata:
  name: loadBlancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    department: prod
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 50001
